//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by Cake.
// </auto-generated>
//------------------------------------------------------------------------------
using System.Reflection;
using System.Runtime.InteropServices;
using System;

[assembly: AssemblyTitle("AngularEventSite")]
[assembly: AssemblyDescription("")]
[assembly: AssemblyCompany("BlueLeet")]
[assembly: AssemblyProduct("AngularEventSite")]
[assembly: AssemblyVersion("1.0.26.0")]
[assembly: AssemblyFileVersion("1.0.26.0")]
[assembly: AssemblyInformationalVersion("1.0.26+Branch.master.Sha.eb2c8a6115922b1b4398cefd0dca326199e59375")]
[assembly: AssemblyCopyright("Copyright ©  2016")]
[assembly: AssemblyTrademark("")]
[assembly: AssemblyConfiguration("")]
[assembly: Guid("c21865a9-d208-410a-bff3-7eec4474f85e")]
[assembly: ComVisible(false)]
[assembly: CLSCompliant(false)]

